### ISSUE TITLE
Using class decorators causes class to be skipped

### ISSUE THREAD

**Issue by jasonsanjose** [h13i32maru/esdoc#36]
See https://github.com/wycats/javascript-decorators#class-declaration

```
@F("color")
@G
class Foo {
}
```

ESDoc fails to generate any docs for class `Foo`.

**Comment by jasonsanjose** [comment]
To be clear, I'm not looking for support to generate esdoc in this use case, I'm simply hoping for either (A) an error message or (B) silently ignoring the new syntax and continue generating esdoc normally.

**Comment by h13i32maru** [comment]
@jasonsanjose Hi! Thanks for this issue :smile:  
Sorry, I don't have plan to support ES7. Please see https://github.com/h13i32maru/esdoc/issues/29 and [FAQ](https://esdoc.org/faq.html#supported-languages) for more information.

> (A) an error message or (B) silently ignoring the new syntax and continue generating esdoc normally.

Now, the both plan are hard. because Espree(used in ESDoc) doesn't support ES7. So ESDoc can not handle ES7 syntax.

Thanks for your understanding.

**Comment by h13i32maru** [comment]
@jasonsanjose Hi!
I published [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin) :smile:
This plugin enables to generate documentation from source code including ES7.
You can use this plugin with ESDoc@0.2.1

**Comment by jasonsanjose** [comment]
Thanks! I'll try it out this week.

**Comment by h13i32maru** [comment]
:+1:
